name: Setup Conan
description: Install Conan and restore cache

inputs:
  cache-key:
    description: Additional cache key component
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Conan
      shell: bash
      run: pip install -r .github/requirements/conan.txt --require-hashes

    - name: Cache Conan packages
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.conan2/p
        key: conan-${{runner.os}}-${{ inputs.cache-key }}
        restore-keys: |
          conan-${{runner.os}}-${{ inputs.cache-key }}-${{ hashFiles('conanfile.py') }}
          conan-${{ inputs.cache-key }}-
          conan--

    - name: Detect Conan profile
      shell: bash
      run: conan profile detect --force
