name: Package
description: Package Aleph

runs:
  using: composite
  steps:
    - name: Package
      shell: bash
      working-directory: build/Release
      run: |
        cpack

    - name: Attest Binary Package
      uses: actions/attest@v4
      with:
        subject-path: '${{ github.workspace }}/build/Release/aleph-*.7z'

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v7
      with:
        path: ${{ github.workspace }}/build/Release/aleph-*.7z
        archive: false
