name: Aleph Build

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  schedule:
    - cron: '45 5 * * *'

permissions: 
  contents: none

jobs:
  dependencies:
    runs-on: ${{ matrix.os }}
    name: Install Dependencies (${{ matrix.os }}, ${{ matrix.compiler }})
    permissions:
      contents: read
    concurrency:
      group: Dependencies-${{ matrix.os }}-${{ matrix.compiler }}
      cancel-in-progress: false
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            compiler: clang
            cc: clang
            cxx: clang++
          - os: windows-latest
            compiler: MSVC
      fail-fast: false
    
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
 
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          
      - name: Setup Conan (Default Compiler)
        uses: ./.github/actions/setup-conan
        with: 
          cache-key: ${{ matrix.compiler }}

      - name: Setup Conan (Specified Compiler)
          
        uses: ./.github/actions/setup-conan
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        with: 
          cache-key: ${{ matrix.compiler }}

      - name: Install Dependencies
        shell: bash
        run: |
          conan install -b=missing -s compiler.cppstd=20 -s:a build_type=Release

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.os }}-${{ matrix.compiler }}.cdx.json
          path: build/sbom.cdx.json
